name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci
        # Workaround for rollup optional dependencies issue
        npm i @rollup/rollup-linux-x64-gnu --save-optional || true
    
    - name: Run tests
      run: npm test -- --run
    
    - name: Build project
      run: npm run build
    
    - name: Create release archive
      run: |
        cd build
        zip -r ../obbba-household-by-household-${{ github.ref_name }}.zip .
        cd ..
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: obbba-household-by-household-${{ github.ref_name }}.zip
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}